from setuptools import setup, find_packages

setup(
    name="webcanvas",
    version="0.0.3",
    author="iMeanAI",
    description="A toolkit for web agent development and evaluation",
    url="https://github.com/iMeanAI/WebCanvas",
    packages=find_packages(),
    package_data={
        "webcanvas": ["**/*.js"],
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.11",
    install_requires=[
        "Jinja2==3.1.2",
        "json5==0.9.14",
        "retry==0.9.2",
        "sanic==23.6.0",
        "gymnasium",
        "playwright>=1.32.1",
        "Pillow",
        "evaluate",
        "openai",
        "types-tqdm",
        "tiktoken",
        "aiolimiter",
        "beartype==0.12.0",
        "flask",
        "nltk",
        "text-generation",
        "transformers==4.33.2",
        "bs4",
        "lxml",
        "colorlog",
        "toml",
        "argparse",
        "anthropic",
        "google-generativeai",
        "requests_toolbelt",
        "ujson",
    ],
)
